import { ArrowLeft, Clock3, Play } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import MinuteLogo from "@/components/MinuteLogo";
import { loadExercises } from "@/exerciseLibrary";

export default function WorkoutDetails() {
  const [searchParams] = useSearchParams();
  const returnPath = searchParams.get("from") === "workouts" ? "/workouts" : "/program";
  const exercises = loadExercises().slice(0, 4);
  return <div className="min-h-screen bg-[#f8f8f5] text-[#1d2b21]"><header className="border-b border-[#dfe6df] bg-[#f8f8f5] px-5 sm:px-8"><div className="mx-auto flex h-[76px] max-w-[1000px] items-center justify-between"><Link to={returnPath} className="inline-flex items-center gap-2 text-sm font-bold text-[#526258]"><ArrowLeft size={16}/> {returnPath === "/workouts" ? "Workouts" : "Program"}</Link><MinuteLogo compact/><Link to="/workouts/start" className="rounded-md bg-[#2d5b3a] px-4 py-2.5 text-sm font-bold text-white">Start timer</Link></div></header><main className="mx-auto max-w-[1000px] px-5 pb-14 pt-10 sm:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.17em] text-[#7a8a7e]">Strength · 6 exercises</p><h1 className="font-brand text-4xl font-semibold tracking-normal sm:text-5xl">Full Body Foundations</h1><p className="mt-3 max-w-xl text-[15px] leading-6 text-[#6b776e]">A steady full-body session built to help you feel strong, capable, and ready for what’s next.</p></div><div className="inline-flex items-center gap-2 text-sm font-bold text-[#5d6d62]"><Clock3 size={17}/> 45 minutes</div></div><section className="mt-9 space-y-3">{exercises.map((exercise, index) => <article key={exercise.id} className="flex items-center gap-4 rounded-2xl border border-[#e1e6df] bg-white p-4"><div className="grid h-16 w-20 shrink-0 place-items-center overflow-hidden rounded-xl bg-[#dbe8d9]">{exercise.media ? <img src={exercise.media} alt={`${exercise.name} demonstration`} className="h-full w-full object-cover"/> : <Play size={23} fill="currentColor" className="text-[#2d5b3a]"/>}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[0.13em] text-[#829087]">Exercise {index + 1}</p><h2 className="mt-1 text-lg font-bold">{exercise.name}</h2><p className="mt-1 text-sm text-[#718078]">{exercise.detail} · {index % 2 === 0 ? "45 sec" : "12 reps"}</p></div><span className="hidden rounded-full bg-[#eef3ec] px-3 py-1.5 text-xs font-bold text-[#45604b] sm:inline">{exercise.focus}</span></article>)}</section><div className="mt-8 rounded-2xl border border-[#d9e4d9] bg-[#eef3ec] p-5"><p className="text-sm font-bold">Ready to move?</p><p className="mt-1 text-sm text-[#65756a]">The timer starts paused so you can get set before your first exercise.</p><Link to="/workouts/start" className="mt-4 inline-flex rounded-md bg-[#2d5b3a] px-4 py-2.5 text-sm font-bold text-white">Start workout</Link></div></main></div>;
}
